export const CHANGE_CURRENCY = "CHANGE_CURRENCY";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";

export const CLEAR_ATTRIBUTES = "CLEAR_ATTRIBUTES";
export const SET_ATTRIBUTE = "SET_ATTRIBUTE";
export const SET_ALL_ATTRIBUTES = "SET_ALL_ATTRIBUTES";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INCREASE_PRODUCT_COUNT = "INCREASE_PRODUCT_COUNT";
export const DECREASE_PRODUCT_COUNT = "DECREASE_PRODUCT_COUNT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const TOGGLE_MINI_CART_STATUS = "TOGGLE_MINI_CART_STATUS";
export const CLOSE_MINI_CART = "CLOSE_MINI_CART";
