export const CHANGE_CURRENCY = "CHANGE_CURRENCY";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";

export const SET_ATTRIBUTE = "SET_ATTRIBUTE";
export const CLEAR_ATTRIBUTES = "CLEAR_ATTRIBUTES";
